### PR TITLE
Don't add class="" to label if no classes specified.

### LINKED ISSUE #382: Empty class on labels
Master is currently generating `class=""` on labels. I'll submit a PR to remove it.

### PR DESCRIPTION
**Pull request by lcreid**
Check if any classes actually make it through to the label, so we don't generate a useless `class=""` on the label. Fixing this fixes a lot of `form_with` test cases that haven't yet been merged.

Fixes #382.

### CODE REVIEW

**Comment by GBH** [comment]
:+1:

**Comment by mattbrictson** [comment]
It looks like Travis is down; hopefully that gets fixed soon and then I'll merge this in.

In the meantime: do you know if this problem pre-dated the v4 changes? I.e. was it a problem in 2.7.0? If so we should mention the fix in the CHANGELOG.

Thanks for the PR!

**Comment by lcreid** [comment]
Looking at the test cases in the legacy branch, I don't see `class=""` in the expected strings, so I don't think we need to mention anything in the CHANGELOG.

**Comment by mattbrictson** [comment]
Can you resolve the merge conflict? (Due to #381 that was just merged)

**Pull request merged**
