### PR TITLE
Rails 5 Support

### PR DESCRIPTION
**Pull request by koenpunt**
With Rails 5 around the corner, I've removed deprecated functions, and made use of new functionality like `Module#prepend`.

**EDIT**

Oh well, it seems I overlooked some other PR's. (namely #267 #248)

### CODE REVIEW

**Comment by beydogan** [comment]
This can be used by adding following line to your gemfile;

```
gem "bootstrap_form", github: "fetch/rails-bootstrap-forms", branch: "rails-5"
```

**Comment by mattbrictson** [comment]
@koenpunt Since #267 has been merged, can we close this PR? If there is more needed to support Rails 5, let me know and I'll do my best to review and merge it in. Thanks!

**Comment by koenpunt** [comment]
No, your branch was sufficient, thanks!

**Comment by koenpunt** [comment]
Although, if the test/dummy application gets updated to rails 5, my updated specs could come in handy

**Comment by mattbrictson** [comment]
> if the test/dummy application gets updated to rails 5, my updated specs could come in handy

@koenpunt OK, can you make a note of that in issue #273? Thanks!

**Comment by koenpunt** [comment]
Turns out I was too quick with saying all was fine, because I didn't update my Gemfile yet, and it was still using a GitHub source. 

When I use the bundled gem again, my tests produce a lot of errors, although I'm not sure what's causing them exactly, so will have to investigate.

**Pull request closed without merging**
