### PR TITLE
Support :prepend and :append for the `select` helper

### LINKED ISSUE #147: Support :append for the `select` helper
Is there an easy way to append label to form select helper?  The following does not seem to work...

```
<%
    options = [['first', 1]]
    (2..30).each {|day| options << [day.to_s, day]}
    options << ['last', 31]
%>
<%= f.select :due_day, options, append: 'day', label: 'Due Day' %>
```

### PR DESCRIPTION
**Pull request by donv**
Fixes #147 for Bootstrap 4

### CODE REVIEW

**Comment by mattbrictson** [comment]
Thanks for putting this together! Can you take a look into the test failure?

**Comment by mattbrictson** [comment]
Looks good 👍

**Comment by lcreid** [comment]
@donv, was there a reason why this was only added for `select`, and not `collection_select` or `grouped_collection_select`?

**Comment by donv** [comment]
No, no reason.

**Pull request merged**
