### PR TITLE
[v4] Removing glyphicon option

### PR DESCRIPTION
**Pull request by GBH**
Glyphicons are not part of Bootstrap4 and markup generated is not a thing anymore.

### CODE REVIEW

**Comment by mattbrictson** [comment]
Thanks for the PR! Could you add a CHANGELOG entry? I think people upgrading would find it useful to know that the `:icon` option is no longer supported.

**Comment by GBH** [comment]
Added to changelog

**Comment by mattbrictson** [comment]
Could you fix the conflicts? Thanks!

**Comment by GBH** [comment]
Conflicts resolved.

**Comment by mattbrictson** [comment]
🙌

**Pull request merged**
