### PR TITLE
Support HTML in help translations.

### PR DESCRIPTION
**Pull request by unikitty37**
Currently, to use HTML in a help text that's stored in a translation, you would need to manually retrieve the translation and either wrap it with `raw()` or append `.html_safe` — the benefits of rails-bootstrap-forms being able to automatically retrieve the help text are lost. This PR allows translations to be marked as containing HTML.

In keeping with convention, the presence of HTML in a translation is
signalled by appending '_html' to the key name. It will then not be
escaped.

### CODE REVIEW

**Comment by edwardmp** [comment]
Would be great if this can be merged in :)

**Comment by unikitty37** [comment]
I'll have a look at Bootstrap 4 compatibility now.

There's already a note added to README.md in a46a3ad1be62b680a4a50ccca650b2f42372d06d — is that text OK?

**Comment by unikitty37** [comment]
This is puzzling me — I had to add d31f240afdb91682b758cfe12569a561346c48a6 to get the Travis builds to pass with Rails 4.0 and 4.1, but this seems to be causing test fails with Bootstrap 4.

Could somebody point me at what I *should* be doing here?

**Comment by mattbrictson** [comment]
@unikitty37 we are going to drop Rails < 5 from the Travis matrix soon, so don't worry about failures for 4.0 and 4.1.

**Comment by mattbrictson** [comment]
@unikitty37 could you rebase your branch off of the latest `master` so we can verify tests pass against the latest code?

@lcreid was there anything else you wanted to see before approving this PR?

**Comment by unikitty37** [comment]
Unfortunately I tried to rebase but it failed, and merge seems to have messed it up. What's the best way forward here? (and is there a guide to rebasing from the original repo? Github's docs use merges…)

**Comment by GBH** [comment]
`git fetch upstream/master && git merge upsteam/master` created this mess?  My git knowledge is restricted to like 3 commands. I'd revert back to the commit before failed merge and try again with random things founds on stackoverflow.

**Comment by mattbrictson** [comment]
No worries. Nothing is ever really _lost_ in git. If the merge/rebase doesn't work, I can reconstruct a clean commit history and merge this in over the weekend.

**Comment by mattbrictson** [comment]
Merged as 4622999. Thanks for the PR and congratulations on your first contribution to the project! 🎉

**Pull request closed without merging**
