### PR TITLE
Getting rid of alias_method_chain

### PR DESCRIPTION
**Pull request by GBH**
Heya,

So Rails 5 is coming out eventually, and `alias_method_chain` is not a thing for a very long time now. This PR removes the need for it. Also I moved setup helper method so it's not global.

Cheers.

### CODE REVIEW

**Comment by fabn** [comment]
:+1:

**Comment by Elektron1c97** [comment]
Is there anything I can do to move this forward?
At the moment there are about 12 deprecation warnings when starting tests in rails 5.

**Comment by wndxlori** [comment]
It would sure be nice to fix this conflict and get this PR merged.

**Comment by mattbrictson** [comment]
I'm planning to close this PR in favor of merging #267. Please let me know if you disagree.

**Comment by wndxlori** [comment]
#267 looks good to me.

**Comment by mattbrictson** [comment]
Closed in favor of #267

**Pull request closed without merging**
