### PR TITLE
Allow to work with Rails5

### PR DESCRIPTION
**Pull request by narugami**
This commit becomes to be compatible with Rails5, but requires Rails4.2+ and Ruby2.2+.

Related issues: #253 , #248.

### CODE REVIEW

**Comment by Elektron1c97** [comment]
I don't think this is going to be merged.
I think you'll have to support legacy stuff too..
See https://github.com/getsentry/raven-ruby/commit/8d8e34cfe33d3af2e3ab3270250e6822ef378bc7

**Comment by benpolinsky** [comment]
+1

**Comment by dankohn** [comment]
Hi, I can confirm that this pull request enables the use of rails-bootstrap-forms with Rails 5, eliminating the 20 errors of `DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top (required)> at /Users/dan/Dropbox/Documents/dev/cii-best-practices-badge/config/application.rb:8)`.

You can include it in your Gemfile with:
```ruby
gem 'bootstrap_form', git: 'https://github.com/narugami/rails-bootstrap-forms',
                      ref: '0d8607f'
```

**Comment by mattbrictson** [comment]
Here's an alternative PR that fixes the deprecation warnings but maintains Ruby 1.9 compatibility: #267.

**Comment by mattbrictson** [comment]
I'm planning to close this PR in favor of merging #267. Please let me know if you disagree.

**Comment by mattbrictson** [comment]
Closed in favor of #267

**Pull request closed without merging**
