### PR TITLE
hook include of helper to loading of ActionView

### PR DESCRIPTION
**Pull request by koenpunt**
this prevents errors with load order of helpers when using rspec for tests.

I also think this should be the way to go for loading extensions.

This is small part of the changes from my previous PR #269

### CODE REVIEW

**Comment by mattbrictson** [comment]
Looks good. Do you think this warrants a mention in the changelog?

**Comment by koenpunt** [comment]
I think not, because this helper is only used within ActionView, right? So without ActionView being loaded, there's no use in having these helpers available.

**Comment by koenpunt** [comment]
We might consider moving it to an initializer in the railtie:

```rb
module BootstrapForm
  module Rails
    class Engine < ::Rails::Engine
      initialize "bootstrap_form.action_view" do
        ActiveSupport.on_load(:action_view) do
          include BootstrapForm::Helper
        end
      end
    end
  end
end

**Comment by mattbrictson** [comment]
I am not entirely familiar with the load order problem you are addressing with this, so please go with whatever you think works best. From a code style standpoint, I prefer the `::Rails::Engine` approach, since that seems to be the "Rails way" to do it.

**Comment by koenpunt** [comment]
I will try to setup a sample app which demonstrates the issue.

**Comment by koenpunt** [comment]
I've setup a sample app with some instructions in the README: https://github.com/koenpunt/bootstrap-forms-test

**Comment by mattbrictson** [comment]
Thanks for the sample app. I see exactly the problem you've described.

Would you like me to merge this as-is, or did you want to switch to the `::Rails::Engine` initializer?

**Comment by koenpunt** [comment]
Not sure, but I had a similar issue with the SimpleForm gem, so I'll check if that's the case. If so then I will put it up on the Rails mailing list to see if can get some insight in why this happens and what the recommended way of fixing is

**Comment by koenpunt** [comment]
Turns out it is a problem being introduced by `rails-controller-testing` https://github.com/rails/rails-controller-testing/issues/24#issuecomment-231738446, and using `on_load` is the recommended way of loading.
Still not sure if it should be in the initializer or not...

**Comment by koenpunt** [comment]
I've got an answer from @rafaelfranca on the matter:

> It depends, if action view is not required to the gem work in a railtie. One example of this is the observers initializer we have in activeresource. You can make activeresource work without observers.

> If the gem only works if action view is present it can be in the place that do the inclusion, in the case in the lib file.

**Comment by koenpunt** [comment]
Done!

**Comment by mattbrictson** [comment]
Thanks! 🙇

**Pull request merged**
