### PR TITLE
Bootstrap V4 support

### PR DESCRIPTION
**Pull request by desheikh**
This includes:
basic class name changes
support for horizontal forms
correct error classes on form inputs and labels
checkbox/radio class name changes

### CODE REVIEW

**Comment by donv** [comment]
Hi!

Any chance this could be merged?

 Would you like help with maintenance?

**Comment by desheikh** [comment]
@mattbrictson, looks like a lot of PR's for bootstrap 4 have come in, some of if unfortunately duplicate work.
Would be great if we can review and get them merge into the bootstrap-v4 so people can continue building on top. Happy to help out in any way.

**Comment by mattbrictson** [comment]
@donv @desheikh Thanks for the offers to help. Bootstrap v4 is a big undertaking, and I have not been keeping up with the changes that v4 is bringing. Even now I am reading that there are still [fundamental changes](https://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/) being made, so it seems like a moving target.

If you both consider this PR ready to go, I will merge it.

If you have time to review other v4 PRs as well, please do and add comments or 👍 if you feel those are good to merge too. I'll rely on you to do the heavy lifting.

Also, longer term I'd like to invite more maintainers to the project, but since I lack admin rights it is a bit out of my control at the moment. Thanks for your patience!

**Comment by desheikh** [comment]
@mattbrictson, @donv I'm comfortable with these changes, as they're already working fine for me with alpha5 on a production app. Happy to help out with the other branches getting merged in as well.

**Comment by mattbrictson** [comment]
Alright, I'll merge this one in. Thanks for your help @desheikh and @donv !

**Pull request merged**
